### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by kokonut27** [kokonut27/zsq#5]
Todo:
* [x] #1 
  * [x] Fix printing input value
  * [x] Fix printing functions value
* [x] #2 
  * [x] Create easy alternative to solve this
* [x] #3
  * [x] Create print function
  * [x] Create prompt function
  * [x] Create cprompt function  
  * [x] Create variables function
  * [x] Create multiline comment
  * [ ] Create while statement
  * [ ] Create whatif statement
    * [ ] #12 
  * [ ] Create range statement
  * [ ] Create function function
  * [ ] Create adding math
  * [x] Create time module and functions
  * [ ] Create os module and functions
    * [ ] #13 
* [x] #4 
  * [ ] Insert images
  * [ ] Insert the real information
  * [x] Add code examples
  * [ ] Add code
  * [ ] Add contact information
  * [ ] Add tutorials page
  * [x] Fix github deployment
